# https://docs.gitlab.com/ci/inputs/
spec:
  inputs:
    editions:
      type: array
      description: List of module editions
      default:
        - ee
        - fe
        - se
        - se-plus

---

PROD | Deploy to Alpha:
  extends: .deploy_prod
  variables:
    RELEASE_CHANNEL: alpha
  parallel:
    matrix:
      - EDITION: $[[ inputs.editions ]]

PROD | Deploy to Beta:
  extends: .deploy_prod
  variables:
    RELEASE_CHANNEL: beta
  parallel:
    matrix:
      - EDITION: $[[ inputs.editions ]]

PROD | Deploy to EarlyAccess:
  extends: .deploy_prod
  variables:
    RELEASE_CHANNEL: early-access
  parallel:
    matrix:
      - EDITION: $[[ inputs.editions ]]

PROD | Deploy TO Stable:
  extends: .deploy_prod
  variables:
    RELEASE_CHANNEL: stable
  parallel:
    matrix:
      - EDITION: $[[ inputs.editions ]]

PROD | Deploy to RockSolid:
  extends: .deploy_prod
  variables:
    RELEASE_CHANNEL: rock-solid
  parallel:
    matrix:
      - EDITION: $[[ inputs.editions ]]
