# https://docs.gitlab.com/ci/inputs/
spec:
  inputs:
    editions:
      type: array
      description: List of module editions
      default:
        - ee
        - fe
        - se
        - se-plus

---

Deploy to PROD | Alpha:
  extends: .deploy_prod
  variables:
    RELEASE_CHANNEL: alpha
  parallel:
    matrix:
      - EDITION: $[[ inputs.editions ]]

Deploy to PROD | Beta:
  extends: .deploy_prod
  variables:
    RELEASE_CHANNEL: beta
  parallel:
    matrix:
      - EDITION: $[[ inputs.editions ]]

Deploy to PROD | EarlyAccess:
  extends: .deploy_prod
  variables:
    RELEASE_CHANNEL: early-access
  parallel:
    matrix:
      - EDITION: $[[ inputs.editions ]]

Deploy to PROD | Stable:
  extends: .deploy_prod
  variables:
    RELEASE_CHANNEL: stable
  parallel:
    matrix:
      - EDITION: $[[ inputs.editions ]]

Deploy to PROD | RockSolid:
  extends: .deploy_prod
  variables:
    RELEASE_CHANNEL: rock-solid
  parallel:
    matrix:
      - EDITION: $[[ inputs.editions ]]
