# https://docs.gitlab.com/ci/inputs/
spec:
  inputs:
    editions:
      type: array
      description: List of module editions
      default:
        - ee
        - fe
        - se
        - se-plus

---
Create gitlab release:
  stage: deploy
  # image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$/
  script:
    - glab release create $CI_COMMIT_TAG
    # - echo "running release job"
  # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
  # release:
  #   tag_name: '$CI_COMMIT_TAG'
  #   description: '$CI_COMMIT_TAG'

Deploy to PROD:
  extends: .deploy_prod
  needs:
    - Create gitlab release
  parallel:
    matrix:
      - EDITION: $[[ inputs.editions ]]
        RELEASE_CHANNEL: [alpha, beta, early-access, stable, rock-solid]
