# Deploy to PROD EE:
#   extends: .deploy_prod
#   variables:
#     EDITION: ee
#   parallel:
#     matrix:
#       - RELEASE_CHANNEL: [alpha, beta, early-access, stable, rock-solid]

Deploy to PROD FE:
  extends: .deploy_prod
  variables:
    EDITION: fe
  parallel:
    matrix:
      - RELEASE_CHANNEL: [alpha, beta, early-access, stable, rock-solid]

Deploy to PROD SE:
  extends: .deploy_prod
  variables:
    EDITION: se
  parallel:
    matrix:
      - RELEASE_CHANNEL: [alpha, beta, early-access, stable, rock-solid]

Deploy to PROD SE+:
  extends: .deploy_prod
  variables:
    EDITION: se-plus
  parallel:
    matrix:
      - RELEASE_CHANNEL: [alpha, beta, early-access, stable, rock-solid]

