Scheduled cleanup:
  stage: cleanup
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: on_success
    - when: never
  before_script:
    - !reference [.setup, before_script]
  script:
    - werf managed-images ls
    - werf cleanup

Auto cleanup:
  stage: cleanup
  allow_failure: true
  timeout: 10 minutes
  rules:
    # do not run if this job is explicitly disabled by user
    - if: $AUTO_CLEANUP == "false" || $AUTO_CLEANUP == "0" || $AUTO_CLEANUP == ""
      when: never
    # do not run if there is a tag (release workflow)
    - if: $CI_COMMIT_TAG
      when: never
    - !reference [.default_rules, rules]
  before_script:
    - !reference [.setup, before_script]
  script:
    - |
      if (( $(date +%s) % 10 == 0 )); then
        echo "✨ Run auto cleanup"
        werf managed-images ls
        werf cleanup
      fi
