spec:
  inputs:
    tag_regex:
    branch_regex:

# for info about expand_vars see https://docs.gitlab.com/ci/yaml/inputs/#expand_vars
.build:
  stage: build
  rules:
    # run if tag match with regex
    - if: '"$CI_COMMIT_TAG" =~ /^($[[ inputs.tag_regex | expand_vars ]])$/'
      when: on_success
    # run if branch name match with regex
    - if: '"$CI_COMMIT_BRANCH" =~ /^($[[ inputs.branch_regex | expand_vars ]])$/'
      when: on_success
    # do not run in other cases
    - when: never
  before_script:
    - !reference [.setup, before_script]
  script:
    # Build images
    - |
      werf build \
        --save-build-report --build-report-path images_tags_werf.json
  artifacts:
    paths:
      - images_tags_werf.json
    expire_in: "30 days"
