.cve_scan:
  variables:
    SOURCE_TAG: ""
    CASE: ""
    EXTERNAL_MODULE_NAME: ""
    VAULT_ROLE: ""
    VAULT_ADDR: https://seguro.flant.com
    DD_URL: "vault:projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets#DD_URL"
    DD_TOKEN: "vault:projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets#DD_TOKEN"
    CVE_TEST_REPO_GIT: "vault:projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets#CVE_TEST_REPO_GIT"
    CVE_TEST_SSH_PRIVATE_KEY: "vault:projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets#CVE_TEST_SSH_PRIVATE_KEY"
    CODEOWNERS_REPO_TOKEN: "vault:projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets#CODEOWNERS_REPO_TOKEN"
    DECKHOUSE_PRIVATE_REPO: "vault:projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets#DECKHOUSE_PRIVATE_REPO"
    TRIVY_PROD_REGISTRY: "vault:projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets#TRIVY_PROD_REGISTRY"
    TRIVY_PROD_REGISTRY_USER: "vault:projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets#TRIVY_PROD_REGISTRY_USER"
    TRIVY_PROD_REGISTRY_PASSWORD: "vault:projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets#TRIVY_PROD_REGISTRY_PASSWORD"
    PROD_REGISTRY: "vault:projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets#PROD_READ_REGISTRY"
    PROD_REGISTRY_USER: "vault:projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets#PROD_READ_REGISTRY_USER"
    PROD_REGISTRY_PASSWORD: "vault:projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets#PROD_READ_REGISTRY_PASSWORD"
    DEV_REGISTRY: "vault:projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets#DEV_REGISTRY_HOST"
    DEV_REGISTRY_USER: "vault:projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets#DEV_REGISTRY_USER"
    DEV_REGISTRY_PASSWORD: "vault:projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Trivy_CVE_Scan_CI_Secrets#DEV_REGISTRY_PASSWORD"
    SCAN_USERS: "False"
    SCAN_SEVERAL_LATEST_RELEASES: "False"
    LATEST_RELEASES_AMOUNT: "3"
    MODULE_PROD_REGISTRY_CUSTOM_PATH: "deckhouse/fe/modules"
    MODULE_DEV_REGISTRY_CUSTOM_PATH: "sys/deckhouse-oss/modules"
    DIGEST_FROM_WERF: "images_tags_werf"
    TRIVY_REPORTS_LOG_OUTPUT: "1"
    WORKDIR: "cve-scan"
    CONFIGMAP_PROJECT_ID: "4352"
    TRIVY_BIN_VERSION: "v0.67.2"
    TRIVY_REPO_ID: "2181"

  id_tokens:
    VAULT_ID_TOKEN:
      aud: gitlab-access-aud

  before_script:
    - |
      set -e
      echo "Installing d8-cli"
      export D8_VERSION="v0.29.24"
      echo "D8_VERSION: $D8_VERSION"
      mkdir -p ~/bin
      D8_BIN=~/bin/d8-${D8_VERSION}
      if [ ! -x "$D8_BIN" ]; then
        curl --fail --show-error -L "https://github.com/deckhouse/deckhouse-cli/releases/download/${D8_VERSION}/d8-${D8_VERSION}-linux-amd64.tar.gz" -o d8-${D8_VERSION}-linux-amd64.tar.gz
        if [[ $? -ne 0 ]]; then echo "curl != 200"; exit 1; fi
        tar --strip-components=2 -xzf d8-${D8_VERSION}-linux-amd64.tar.gz linux-amd64/bin/d8
        mv d8 "${D8_BIN}"
        chmod u+x "${D8_BIN}"
      fi
      echo "D8_BIN: $D8_BIN"

      echo "Writing vault token"
      export VAULT_TOKEN=$(${D8_BIN} stronghold write -field=token auth/fox/login role=$VAULT_ROLE jwt=$VAULT_ID_TOKEN)
      while IFS='=' read -r name value; do
        # Проверяем, начинается ли значение с 'vault:'
        if [[ $value == vault:* ]]; then
          # Удаляем префикс 'vault:'
          stripped_value=${value#vault:}
          secret_path="${stripped_value%%#*}"
          secret_value=$(${D8_BIN} stronghold read -field=data --format=json "${secret_path}" | jq --arg v "${stripped_value#*#}" '.[$v]' -r)
          export "$name=${secret_value}"
        fi
        
      done < <(env)
      echo "Variables written to environment"

      echo "Adding ssh key to ~/.ssh"
      mkdir -p ~/.ssh
      chmod 700 ~/.ssh
      printf '%s\n' "$CVE_TEST_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      HOST=$(echo "$CVE_TEST_REPO_GIT" | sed -E 's/.*@([^:]+).*/\1/')
      if [ -n "$HOST" ]; then
        ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts 2>/dev/null || true
      fi
      echo "Known hosts file updated"

      echo "Cloning cve-scripts repository"
      rm -rf /tmp/cve-scripts
      git clone --depth 1 "$CVE_TEST_REPO_GIT" /tmp/cve-scripts
      cp /tmp/cve-scripts/*.sh /tmp/cve-scripts/*.py .
      chmod +x *.sh *.py
      echo "Scripts copied to current directory"
  script:
    - |
      export SOURCE_TAG
      export CASE
      export EXTERNAL_MODULE_NAME
      export RELEASE_IN_DEV
      export SCAN_USERS
      export SCAN_SEVERAL_LATEST_RELEASES
      export LATEST_RELEASES_AMOUNT
      export TRIVY_PROD_REGISTRY
      export TRIVY_BIN_VERSION
      export TRIVY_REPO_ID
      export TRIVY_REPORTS_LOG_OUTPUT
      export PROD_REGISTRY
      export PROD_REGISTRY_USER
      export PROD_REGISTRY_PASSWORD
      export DEV_REGISTRY
      export DEV_REGISTRY_USER
      export DEV_REGISTRY_PASSWORD
      export MODULE_PROD_REGISTRY_CUSTOM_PATH
      export MODULE_DEV_REGISTRY_CUSTOM_PATH
      export DIGEST_FROM_WERF
      export DD_URL
      export DD_TOKEN
      export CODEOWNERS_REPO_TOKEN
      export DECKHOUSE_PRIVATE_REPO
      export CONFIGMAP_PROJECT_ID
      export WORKDIR="${CI_PROJECT_DIR}/${WORKDIR}"
      export TRIVY_DB_URL="${TRIVY_PROD_REGISTRY}/deckhouse/ee/security/trivy-db:2"
      export TRIVY_JAVA_DB_URL="${TRIVY_PROD_REGISTRY}/deckhouse/ee/security/trivy-java-db:1"
      export TRIVY_POLICY_URL="${TRIVY_PROD_REGISTRY}/deckhouse/ee/security/trivy-bdu:1"

      echo "Running cve_scan.sh"
      ls -la ./
      echo "CVE_TEST_REPO_GIT: $CVE_TEST_REPO_GIT"
      echo "DECKHOUSE_PRIVATE_REPO: $DECKHOUSE_PRIVATE_REPO"
      echo "TRIVY_PROD_REGISTRY: $TRIVY_PROD_REGISTRY"
      echo "TRIVY_PROD_REGISTRY_USER: $TRIVY_PROD_REGISTRY_USER"
      echo "PROD_REGISTRY: $PROD_REGISTRY"
      echo "PROD_REGISTRY_USER: $PROD_REGISTRY_USER"

      ls -la ../
      ./cve_scan.sh
