
.cve_scan:
  variables:
    PROD_REGISTRY: ""
    PROD_REGISTRY_USER: ""
    PROD_REGISTRY_PASSWORD: ""
    DEV_REGISTRY: ""
    DEV_REGISTRY_USER: ""
    DEV_REGISTRY_PASSWORD: ""
    DD_URL: ""
    DD_TOKEN: ""
    SOURCE_TAG: ""
    CASE: ""
    EXTERNAL_MODULE_NAME: ""
    RELEASE_IN_DEV: "false"
    SCAN_USERS: "false"
    SCAN_SEVERAL_LATEST_RELEASES: "false"
    LATEST_RELEASES_AMOUNT: "3"
    MODULE_PROD_REGISTRY_CUSTOM_PATH: "deckhouse/fe/modules"
    MODULE_DEV_REGISTRY_CUSTOM_PATH: "sys/deckhouse-oss/modules"
    DIGEST_FROM_WERF: "images_tags_werf"
    TRIVY_REPORTS_LOG_OUTPUT: "2"
    WORKDIR: "cve-scan"
    CVE_TEST_REPO_GIT: ""
    CVE_SSH_PRIVATE_KEY: ""
    CODEOWNERS_REPO_TOKEN: ""
    DECKHOUSE_PRIVATE_REPO: ""
    CONFIGMAP_PROJECT_ID: "4352"
    TRIVY_BIN_VERSION: "v0.67.2"
    TRIVY_REPO_ID: "2181"
    TRIVY_DB_URL: "${PROD_REGISTRY}/deckhouse/ee/security/trivy-db:2"
    TRIVY_JAVA_DB_URL: "${PROD_REGISTRY}/deckhouse/ee/security/trivy-java-db:1"
    TRIVY_POLICY_URL: "${PROD_REGISTRY}/deckhouse/ee/security/trivy-bdu:1"

  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$CVE_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - |
      HOST=$(echo "$CVE_TEST_REPO_GIT" | sed -E 's/.*@([^:]+).*/\1/')
      ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts 2>/dev/null

    - rm -rf /tmp/cve-scripts
    - git clone --depth 1 $CVE_TEST_REPO_GIT /tmp/cve-scripts
    - cp /tmp/cve-scripts/*.sh /tmp/cve-scripts/*.py .
    - chmod +x *.sh *.py

  script:
    - |
      export SOURCE_TAG
      export CASE
      export EXTERNAL_MODULE_NAME
      export RELEASE_IN_DEV
      export SCAN_USERS
      export SCAN_SEVERAL_LATEST_RELEASES
      export LATEST_RELEASES_AMOUNT
      export TRIVY_BIN_VERSION
      export TRIVY_REPO_ID
      export TRIVY_DB_URL
      export TRIVY_JAVA_DB_URL
      export TRIVY_POLICY_URL
      export TRIVY_REPORTS_LOG_OUTPUT
      export PROD_REGISTRY
      export PROD_REGISTRY_USER
      export PROD_REGISTRY_PASSWORD
      export DEV_REGISTRY
      export DEV_REGISTRY_USER
      export DEV_REGISTRY_PASSWORD
      export MODULE_PROD_REGISTRY_CUSTOM_PATH
      export MODULE_DEV_REGISTRY_CUSTOM_PATH
      export DIGEST_FROM_WERF
      export DD_URL
      export DD_TOKEN
      export CODEOWNERS_REPO_TOKEN
      export DECKHOUSE_PRIVATE_REPO
      export CONFIGMAP_PROJECT_ID
      export WORKDIR="${CI_PROJECT_DIR}/${WORKDIR}"
      
      ./cve_scan.sh