# variables:
#   $MODULES_REGISTRY - base URL for the registry, e.g., registry.example.com
#   $MODULES_REGISTRY_PATH - registry path to the module source, e.g., /deckhouse/modules
#   $MODULES_MODULE_NAME (Optional) - module name, by default it is equal to the project name
#   $RELEASE_CHANNEL - lowercase release channel name, e.g., alpha, stable, early-access


.deploy:
  variables:
    WERF_REPO: "${MODULES_REGISTRY}/${MODULES_REGISTRY_PATH}/${MODULES_MODULE_NAME}"
    IMAGE_SRC: "${WERF_REPO}/release:${CI_COMMIT_REF_NAME}"
    IMAGE_DST: "${WERF_REPO}/release:${RELEASE_CHANNEL}"
  stage: deploy
  script:
  - crane copy "${IMAGE_SRC}" "${IMAGE_DST}"
  only:
    - tags
  except:
    - main
  when: manual
