# variables:
#   $MODULES_MODULE_SOURCE - base URL for the registry, e.g., registry.example.com/deckhouse/modules
#   $MODULES_MODULE_NAME (Optional) - module name, by default it is equal to the project name
#   $RELEASE_CHANNEL - lowercase release channel name, e.g., alpha, stable, early-access


.deploy:
  stage: deploy
  script:
  - |
    REPO="${MODULES_MODULE_SOURCE}/${MODULES_MODULE_NAME}/release"

    IMAGE_SRC="${REPO}:${MODULES_MODULE_TAG}"
    IMAGE_DST="${REPO}:${RELEASE_CHANNEL}"

    echo "✨ Pushing ${IMAGE_SRC} to ${IMAGE_DST}"
    crane copy "${IMAGE_SRC}" "${IMAGE_DST}"
  rules:
    - if: $CI_COMMIT_TAG
  when: manual
