# variables:
#   $MODULES_MODULE_SOURCE - base URL for the registry, e.g., registry.example.com/deckhouse/modules
#   $MODULES_MODULE_NAME (Optional) - module name, by default it is equal to the project name
#   $RELEASE_CHANNEL - lowercase release channel name, e.g., alpha, stable, early-access


.deploy:
  variables:
    WERF_REPO: "${MODULES_MODULE_SOURCE}/${MODULES_MODULE_NAME}"
    IMAGE_SRC: "${WERF_REPO}/release:${CI_COMMIT_REF_NAME}"
    IMAGE_DST: "${WERF_REPO}/release:${RELEASE_CHANNEL}"
  stage: deploy
  script:
  - |
    echo "✨ Pushing ${IMAGE_SRC} to ${IMAGE_DST}"
    crane copy "${IMAGE_SRC}" "${IMAGE_DST}"
  only:
    - tags
  except:
    - main
  when: manual
