# D8_VERSION - optional variable to download specific version of the

.import_secrets:
  before_script:
    - |
      # Setup secrets
      if [ -z "${D8_VERSION}" ]; then
        D8_VERSION=$(curl -sSL https://api.github.com/repos/deckhouse/deckhouse-cli/releases/latest | jq -r '.tag_name')
      fi

      mkdir -p ~/bin
      D8_BIN=~/bin/d8-${D8_VERSION}

      if [ ! -x "$D8_BIN" ]; then
        curl --fail --show-error -L "https://github.com/deckhouse/deckhouse-cli/releases/download/${D8_VERSION}/d8-${D8_VERSION}-linux-amd64.tar.gz" -o d8-${D8_VERSION}-linux-amd64.tar.gz
        if [[ $? -ne 0 ]]; then echo "curl != 200"; exit 1; fi
        tar --strip-components=2 -xzf d8-${D8_VERSION}-linux-amd64.tar.gz linux-amd64/bin/d8
        mv d8 ${D8_BIN}
        chmod u+x ${D8_BIN}
      fi

      export VAULT_TOKEN=$(${D8_BIN} stronghold write -field=token auth/fox/login role=$VAULT_ROLE jwt=$VAULT_ID_TOKEN)

      while IFS='=' read -r name value; do
        # Проверяем, начинается ли значение с 'vault:'
        if [[ $value == vault:* ]]; then
          # Удаляем префикс 'vault:'
          stripped_value=${value#vault:}
          secret_path="${stripped_value%%#*}"
          secret_value=$(${D8_BIN} stronghold read -field=data -format=json "${secret_path}" | jq --arg v "${stripped_value#*#}"  '.[$v]' -r )
          export "$name=${secret_value}"
        fi
      done < <(env)