.lint:
  stage: lint
  rules:
    # run if push to a branch
    - if: '$CI_COMMIT_BRANCH'
      when: on_success
    # run if module tag defined (module release)
    - if: '$CI_COMMIT_TAG'
      when: on_success
    # do not run in other cases
    - when: never

  allow_failure: true
  before_script:
    - !reference [.setup, before_script]
  script:
    - |
      dmt lint ./
