# Semgrep static analysis: SARIF report packed with source, upload via Svacer API.
# Script semgrep_analyze.py discovers semgrep.yml/semgrep.yaml in the repo (or under SEMGREP_CONFIG_SEARCH_DIR).
#
# Required variables (set in project or when running the job):
#   VAULT_ADDR             - seguro URL
#   VAULT_ROLE             - name of auth role
#
# Optional variables:
#   SVACER_URL             - full URL of Svacer server, e.g. https://svacer.example.com
#   SVACER_IMPORT_USER     - user for Svacer import
#   SVACER_IMPORT_PASSWORD - password for Svacer import
#   PROJECT_GROUP   - project group in Svacer (default: CI_PROJECT_NAME)
#   IF_NO_GROUP     - action if no project group (default: "add")
#   COMMIT_REF_NAME - branch name (default: CI_COMMIT_REF_NAME)
#   COMMIT_HASH     - commit hash (default: CI_COMMIT_SHA)

stages:
  - static_analysis

semgrep:scan:
  stage: static_analysis
  image: registry.flant.com/deckhouse/ssdlc-tools/semgrep-analyzer:main
  tags:
    - werf-2-stable
  id_tokens:
    VAULT_ID_TOKEN:
      aud: gitlab-access-aud
  variables:
    SVACER_URL: "vault:projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Svace_CI#SVACER_URL"
    SVACER_IMPORT_USER: "vault:projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Svace_CI#SVACER_IMPORT_USER"
    SVACER_IMPORT_PASSWORD: "vault:projects/data/24cb1d7c-717a-4f92-8547-26f632916a7a/Svace_CI#SVACER_IMPORT_PASSWORD"
  before_script:
    - |
      export VAULT_TOKEN=$(d8 stronghold write -field=token auth/fox/login role=$VAULT_ROLE jwt=$VAULT_ID_TOKEN)

      while IFS='=' read -r name value; do
        # Проверяем, начинается ли значение с 'vault:'
        if [[ $value == vault:* ]]; then
          # Удаляем префикс 'vault:'
          stripped_value=${value#vault:}
          secret_path="${stripped_value%%#*}"
          secret_value=$(d8 stronghold read -field=data -format=json "${secret_path}" | jq --arg v "${stripped_value#*#}"  '.[$v]' -r )
          export "$name=${secret_value}"
        fi
      done < <(env)
  script:
    - python3 analyze.py
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH =~ /^release-/'
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+(\.\d+)?$/'
    - when: never
  allow_failure: true
  needs: []
  artifacts:
    when: always
    paths:
      - artifacts
  allow_failure:
    exit_codes: 11